### ISSUE TITLE
libssh2_1.4.1 + Net-SSH2-0.45 Has Problem With scp_get

### ISSUE THREAD

**Issue by angusmcchris** [rkitover/net-ssh2#8] opened 2012-10-10 21:53 UTC
Referencing:  https://rt.cpan.org/Public/Bug/Display.html?id=80011

It seems libssh2_1.4.1 + Net-SSH2-0.45 has a problem with scp_get.  Using strawberry-perl-5.16.1.1-64bit-portable configured with libssh2_1.4.1 + Net-SSH2-0.45, I am unable to scp_get a file.  Using strawberry-perl-5.12.3.0-portable which comes with libssh2_1.2.5 + Net-SSH2-0.33, it works.

Code:

use Net::SSH2;

my ($User, $PW) = ('[UserName]', '[Password]');

my $SSH2 = Net::SSH2->new();
if ($SSH2->connect('[HostName]')) {
    if ($SSH2->auth_password($User, $PW)) {
    my $Chan = $SSH2->channel();
    $Chan->blocking(1);
    my $TmpOutFile = "[FileName]";

    $SSH2->debug(1);
    use IO::Scalar;
    my $FileData = IO::Scalar->new;
    $SSH2->scp_get($TmpOutFile, $FileData);
    print "SSH2 Error: ",$SSH2->error(),"\n";
    my @Data = split(/\n/, $FileData);
    print "Number of Lines:  ",($#Data+1),"\n";

    $Chan->close;
    } else { print "2_Login",join("|",$SSH2->error()), "\n"; }
} else { print "1_Connect",join("|",$SSH2->error()), "\n"; }

$SSH2->disconnect();

Failure Output:

libssh2_scp_recv(ss->session, path, &st) -> 0x26545d8
Net::SSH2::Channel::read(size = 1, ext = 0)
- read 1 bytes
- read 1 total
Net::SSH2::Channel::DESTROY
SSH2 Error: 0
Number of Lines:  0
Net::SSH2::Channel::DESTROY
Net::SSH2::DESTROY object 0x25968f8

I submitted a bug to the Strawberry Perl distribution, and KMX found the following:

perl-5.16.1 + libssh2_1.4.1 + Net-SSH2-0.45 - FAILS
perl-5.16.1 + libssh2_1.4.1 + Net-SSH2-0.33 - FAILS
perl-5.16.1 + libssh2_1.2.8 + Net-SSH2-0.33 - WORKS
perl-5.16.1 + libssh2_1.2.8 + Net-SSH2-0.45 - WORKS

KMX suggested I downrev to libssh2_1.2.8.  I did, and it started working.

Let me know if I can provide any additional information.

Thanks!

angusmcchris

**Comment by salva** [comment] 2015-09-27 14:29
I can't reproduce this issue with the development version of Net::SSH2 and current libssh2 so I'm closing it.

**Closed by salva** 2015-09-27 14:29 UTC
