### ISSUE TITLE
after upgrading from stretch to buster I get: Callback returned error (-19 LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED)

### ISSUE THREAD

**Issue by davewood** [rkitover/net-ssh2#49] opened 2019-07-30 14:18 UTC
this piece of code used to work but now doesnt and I am trying to find out why. I moved from debian stretch to debian buster

Could be possible it has to do with urandom initialization under buster.

```
epplication@cc9c15d7fb80:~/EPPlication$ cat ssh.pl 
use 5.018;
use strict;
use warnings;

use Net::SSH2;
my $command  = 'ls';
my $ssh_host = 'localhost';
my $ssh_port = '22';
my $ssh_user = 'epplication';
my $ssh_public_key_path  = '/home/epplication/EPPlication/ssh_keys/id_rsa.pub';
my $ssh_private_key_path = '/home/epplication/EPPlication/ssh_keys/id_rsa';

my $ssh = Net::SSH2->new(
        debug => 1,
        trace => 1
);

$ssh->connect($ssh_host, $ssh_port)
  or $ssh->die_with_error;

$ssh->auth_publickey(
    $ssh_user,
    $ssh_public_key_path,
    $ssh_private_key_path,
) or $ssh->die_with_error;
```

###########################################

```
epplication@cc9c15d7fb80:~/EPPlication$ perl -I local/lib/perl5/ ssh.pl 
Callback returned error (-19 LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED) at ssh.pl line 21.
Net::SSH2::DESTROY object 0x61aa01a0
```
###########################################
```
epplication@cc9c15d7fb80:~$ ssh -i /home/epplication/EPPlication/ssh_keys/id_rsa   epplication@localhost
Linux cc9c15d7fb80 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Jul 30 13:45:54 2019 from 127.0.0.1
epplication@cc9c15d7fb80:~$ 
```
###########################################
```
epplication@cc9c15d7fb80:~/EPPlication$ ls -lah ssh_keys/
total 16K
drwx------ 2 epplication epplication 4.0K Jul 30 13:19 .
drwxr-xr-x 1 epplication epplication 4.0K Jul 30 13:44 ..
-rw------- 1 epplication epplication 1.8K Jul 30 13:19 id_rsa
-rw-r--r-- 1 epplication epplication  406 Jul 30 13:19 id_rsa.pub
```

**Comment by rkitover** [comment] 2019-07-31 13:29
Try installing the latest libssh2 to /usr/local and installing the module from CPAN.

This error means libssh2 was not able to read the key file format. I believe there is code in 1.9.0 with better OpenSSH key file format support.

**Comment by davewood** [comment] 2019-12-10 13:05
im pretty sure ir worked after updating stuff, thank you for your help.

**Comment by davewood** [comment] 2020-12-07 12:27
i just ran into this problem again and dont know whats left to update.

```
cat /etc/debian_version 
10.6
```

```
$ apt list --installed|grep -i ssh
libssh2-1-dev/stable,now 1.8.0-2.1 amd64 [installed]
libssh2-1/stable,now 1.8.0-2.1 amd64 [installed,automatic]
openssh-client/stable,now 1:7.9p1-10+deb10u2 amd64 [installed,automatic]
openssh-server/stable,now 1:7.9p1-10+deb10u2 amd64 [installed,automatic]
openssh-sftp-server/stable,now 1:7.9p1-10+deb10u2 amd64 [installed,automatic]
ssh/stable,now 1:7.9p1-10+deb10u2 all [installed]
```

```
carton exec perl -MNet::SSH2\ 999
Net::SSH2 version 999 required--this is only version 0.71.
```

```
carton exec perl ssh.pl 
Callback returned error (-19 LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED) at ssh.pl line 21.
Net::SSH2::DESTROY object 0x21c106f0
```

```
/usr/sbin/sshd -dD
debug1: sshd version OpenSSH_7.9, OpenSSL 1.1.1d  10 Sep 2019
debug1: private host key #0: ssh-rsa SHA256:K1o5...
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:6kZ/...
debug1: private host key #2: ssh-ed25519 SHA256:woBM...
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-dD'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
debug1: inetd sockets after dupping: 3, 3        
Connection from 127.0.0.1 port 50964 on 127.0.0.1 port 22
debug1: Client protocol version 2.0; client software version libssh2_1.8.0
debug1: no match: libssh2_1.8.0                  
debug1: Local version string SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
debug1: permanently_set_uid: 102/65534 [preauth] 
debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
debug1: SSH2_MSG_KEXINIT sent [preauth]          
debug1: SSH2_MSG_KEXINIT received [preauth]      
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256 [preauth]
debug1: kex: host key algorithm: ssh-rsa [preauth]
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]
debug1: expecting SSH2_MSG_KEX_DH_GEX_REQUEST [preauth]
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST received [preauth]
debug1: SSH2_MSG_KEX_DH_GEX_GROUP sent [preauth] 
debug1: expecting SSH2_MSG_KEX_DH_GEX_INIT [preauth]
debug1: rekey after 4294967296 blocks [preauth]  
debug1: SSH2_MSG_NEWKEYS sent [preauth]          
debug1: expecting SSH2_MSG_NEWKEYS [preauth]     
debug1: SSH2_MSG_NEWKEYS received [preauth]      
debug1: rekey after 4294967296 blocks [preauth]  
debug1: KEX done [preauth]                       
debug1: userauth-request for user epplication service ssh-connection method publickey [preauth]
debug1: attempt 0 failures 0 [preauth]           
debug1: PAM: initializing for "epplication"      
debug1: PAM: setting PAM_RHOST to "127.0.0.1"    
debug1: PAM: setting PAM_TTY to "ssh"            
debug1: userauth_pubkey: test pkalg ssh-rsa pkblob RSA SHA256:Cv3so... [preauth]
debug1: temporarily_use_uid: 1000/1000 (e=0/0)   
debug1: trying public key file /home/epplication/.ssh/authorized_keys
debug1: fd 4 clearing O_NONBLOCK                 
debug1: /home/epplication/.ssh/authorized_keys:1: matching key found: RSA SHA256:Cv3so...
debug1: /home/epplication/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key RSA SHA256:Cv3s... found at /home/epplication/.ssh/authorized_keys:1
debug1: restore_uid: 0/0                         
Postponed publickey for epplication from 127.0.0.1 port 50964 ssh2 [preauth]
Connection closed by authenticating user epplication 127.0.0.1 port 50964 [preauth]
debug1: do_cleanup [preauth]                     
debug1: monitor_read_log: child log fd closed    
debug1: do_cleanup                               
debug1: PAM: cleanup                             
debug1: Killing privsep child 5036               
debug1: audit_event: unhandled event 12  
```

**Comment by salva** [comment] 2020-12-15 17:24
That error indicates that the public and private keys provided do not match or maybe that there is some problem reading any of them.

Some crypto backends do not really need the public key, so you can try passing undef there.

Otherwise, this looks like a problem in libssh2 (Net::SSH2 `auth_publickey` is a very thin wrapper that just passes the data unchanged to the libssh2 function), so, you may like to ask on the libssh2-devel mailing list. It may be a known issue.

**Comment by salva** [comment] 2020-12-15 17:26
BTW, it seems you are using libssh2 1.8.x instead of the more recent 1.9.0 that you said it had fixed your issue last time.

**Comment by davewood** [comment] 2020-12-18 10:14
I most definitely did not say that I updated to libssh2 1.9.x ... stupid me didnt include what I updated back then.

```
root@befd4da6fd85:/home/epplication/EPPlication# apt search libssh2
Sorting... Done
Full Text Search... Done
libssh2-1/now 1.8.0-2.1 amd64 [installed,local]
  SSH2 client-side library

libssh2-1-dev/now 1.8.0-2.1 amd64 [installed,local]
  SSH2 client-side library (development headers)

root@befd4da6fd85:/home/epplication/EPPlication# cat /etc/debian_version 
10.7
```

I need this to work with debian:buster

the ssh keys im trying to use are created on the same machine. 

`ssh-keygen -b 2048 -t rsa -f /home/epplication/EPPlication/ssh_keys/id_rsa -N ""`

**Comment by salva** [comment] 2020-12-22 15:37
I have been able to reproduce this issue both in Debian and Ubuntu.

The problem is caused by libssh2 being compiled there with the gcrypt backend which doesn't support OpenSSH native private key format.

There are two ways to work around this issue:

1) create the key in PEM format:

        ssh-keygen -b 2048 -t rsa -f $key_path -N "" -m PEM

2) recompile libssh2 using the OpenSSL backend

        $ ./configure --with-crypto=openssl ...

Well, and if you feel brave, you could also add support for OpenSSH native key format into the gcrypt backend!!!

**Comment by salva** [comment] 2020-12-22 15:38
As this is definitively not a limitation of the wrapper but of the libssh2, I am closing the issue.

**Closed by salva** 2020-12-22 15:38 UTC

**Comment by davewood** [comment] 2020-12-27 17:10
`-m PEM` fixes the problem.

i wonder about 2 things. does the gcrypt team care? it worked before and now it doesnt.

thanks for the help

**Comment by salva** [comment] 2020-12-28 09:05
> does the gcrypt team care?

The limitation is not in the gcrypt library but in the glue code for it inside libssh2.

> it worked before and now it doesnt.

I don't think so. The last change to that part of the key handling code is from 2007. Maybe you were already using keys in PEM format or you were using a version of libssh2 compiled with the OpenSSL backend.

**Comment by davewood** [comment] 2020-12-28 13:53
I know it worked before because I run the same code automatically in a docker setup for every release of my repo. something in the chain has changed apparently. docker image, debian, some perl module, ssh-keygen, ...

https://github.com/nic-at/EPPlication/blame/3e10b1e7394fde3b0e463bedabe57691a8c5b5a8/docker_entrypoint.sh#L40

**Comment by salva** [comment] 2020-12-28 15:21
Sorry, I had probably not phrased correctly what I wanted to say. I don't doubt the application was working for you before.

What I wanted to say is that I don't think you could have had a version of Net::SSH2/libssh2 with the gcrypt backend able to read keys on the OpenSSH format because that was never supported by the library. It your application was working for you it is because you had a different setup.
